title: Laura Newman Eckstein 
google_analytics: 
description: Laura Newman Eckstein's personal website
show_downloads: false
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
  - jekyll-twitter-plugin
